### DISCUSSION TITLE
Integer Enums with descriptive names : How ?

### DISCUSSION THREAD

**Discussion by nklamann** [koxudaxi/datamodel-code-generator#2233] [Q&A] [answered]
Hallo all,
I am quite new to the whole area of OpenAPI and try to build the Python classes for an OpenAPI-Specification. 

One problem  is that the integer enums in the schema don't get good names. Consider:  
```yaml
components:
  schemas:
    AccountTypeEnum:
      enum:
      - 1
      - 2
      - 3
      type: integer
      description: |-
        * `1` - IMAP
        * `2` - Gmail OAuth
        * `3` - Outlook OAuth
```
gives:
```python
class AccountTypeEnum(int, Enum):
    INTEGER_1 = 1
    INTEGER_2 = 2
    INTEGER_3 = 3

```
The commandline used was:

```bash
datamodel-codegen \
    --output-model-type pydantic_v2.BaseModel \
    --field-constraints  --use-subclass-enum  \
    --capitalise-enum-members \
    --input ../Paperless-ngx_rest_api_v6.yaml --output datamodel-codegen/paperless_v6_model.py
```

Am  I missing something ?
