### DISCUSSION TITLE
Extra keys when generating models

### DISCUSSION THREAD

**Discussion by gk12277** [koxudaxi/datamodel-code-generator#414] [Q&A] [answered]
Hi,
Is it possible to add extra keys and values when generating models form jsonschema.

eg:
```yaml
---
"$schema": http://json-schema.org/draft-07/schema#
title: Person
type: object
properties:
  firstName:
    type: string
    description: The person's first name.

```

Using this schema  I generated models

```python
# generated by datamodel-codegen:
#   filename:  person.yaml
#   timestamp: 2021-04-22T11:25:47+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Person(BaseModel):
    firstName: Optional[str] = Field(None, description="The person's first name.")

```
Is there a way to  specify key1, key2 and values in my schema so that the model is generated as below
eg:
```python
firstName: Optional[str] = Field(
        None, 
        description="The person's first name.", 
        key1={"a":"a1", "b":"b1"}, 
        key2="aaaa"
   )
```

**Comment by koxudaxi** [comment, marked as answer]
Hi @gk12277 
> Is it possible to add extra keys and values when generating models form jsonschema.

the short answer is no.

> Is there a way to specify key1, key2 and values in my schema so that the model is generated as below

Where are key1, key2?
Did you expect this schema?
```yaml

"$schema": http://json-schema.org/draft-07/schema#
title: Person
type: object
properties:
  firstName:
    type: string
    description: The person's first name.
    key1: 
      a: a1
      b: b1
    key2: aaaa
```

I can add an option of CLI to pass extra keys to the field.
For example
```bash
$ datamodel-codegen --input input.json --extra-keys key1 key2
```

What do you think about it?
