### DISCUSSION TITLE
Option to give custom types

### DISCUSSION THREAD

**Discussion by gk12277** [koxudaxi/datamodel-code-generator#418] [Q&A] [answered]
Hi, is there an option to give custom types?

I want the models to be created in this way.

```python
from random_file import UserType

class User(BaseModel):
    user_type: Optional[UserType] = Field(None)
```
For the import string I have added it in custom template.

I am using jsonschema for generation. Is there a way to specify types like `UserType` in this case.

```yaml
"$schema": http://json-schema.org/draft-07/schema#
type: object
properties:
  User:
    type: object
    properties:
      user_type:
        type:
```

**Comment by balukrishnans** [comment]
Hi,

There is a similar use case for me. I need to give a function as the default value (the importing part is a similar case here). I am also using jsonschema for generating the models. 

#### For example
**foo.py**
``` python
class Foo:
    def bar(self):
        # code here
```

**models.py**
``` python
from foo import Foo

class Baz(BaseModel):
    bar = Foo.bar
```

Is there any way to achieve this?

**Comment by koxudaxi** [comment]
@gk12277 
We need to add a CLI option to support custom types. 
I think we should give a custom type or custom format.
Did you have an idea?

@balukrishnans 
Your situation is more complex.
I guess we can pass custom type by adding a new CLI option. But, you set  `Foo.bar`. it is not `Foo` 🤔 
You may need to create a custom template with jinja2.
There is an option.
` --custom-template-dir`

And, this is the default template.
https://github.com/koxudaxi/datamodel-code-generator/blob/master/datamodel_code_generator/model/template/pydantic/BaseModel.jinja2

**Reply by gk12277** [reply]
@koxudaxi  Is there a way to pass values other than the ones in basic templates from the jsonschema.

**Reply by koxudaxi** [reply]
@gk12277 
> Is there a way to pass values other than the ones in basic templates from the jsonschema.

Nothing :(

I want to set custom type and custom format.
```bash
... --custom-types {"Foo" : "custom.Foo",  "string": {"custom-uri": "custom.Bar" }
```
What did you think about this idea?

But,  `Foo.bar` is not resolved.

**Reply by koxudaxi** [reply]
`Foo.bar` is the default value. It is not `type`.
We probably should separate this problem. 🤔

**Reply by gk12277** [reply]
` --custom-types {"Foo" : "custom.Foo",  "string": {"custom-uri": "custom.Bar" }`

@koxudaxi  Could you pls write the jsonschema and the generated models for this. So i can get a better idea.

**Reply by koxudaxi** [reply]
@gk12277 
Sure!!

## Input
```yaml
"$schema": http://json-schema.org/draft-07/schema#
type: object
properties:
  User:
    type: object
    properties:
      foo:
        type: Foo
      uri:
        type: string
        format: custom-uri
```

## output
```python
from custom import Foo, Bar

class User(BaseModel):
    foo: Optional[Foo] = None
    uri: Optional[Bar] = None
```

I don't know whether writing custom type (`type: Foo`) is valid as JSON schema.

**Reply by gk12277** [reply]
@koxudaxi
Giving `Foo` in type doesn't seem right and also if we pass the types in cli there might be a lot of data to pass.
How about we handle this in json schema itself. Something like this.
eg:

```yaml
"$schema": http://json-schema.org/draft-07/schema#
type: object
properties:
  User:
    type: object
    properties:
      foo:
        format: class
        path: custom.Foo
        type: object  
      bar:
        format: function
        path: custom.bar
        type: object  
```

```python

from custom import Foo

class Foo(BaseModel):
    foo: Optional[Foo] = None
    
```

**Reply by koxudaxi** [reply]
@gk12277 
> How about we handle this in json schema itself. Something like this.

I can implement it.
But, I think users may not want the custom data into JSONSchmea. 
Because, The schema may not be created by the user.
Some users pick up schemas from other projects.

This is my thought and it is not the goal.

**Reply by gk12277** [reply]
@koxudaxi User will only add the custom data in special cases right . So that's why I suggested when users need a special class as type he/she can give `format` as `class` and import statement in `path` key.

**Reply by koxudaxi** [reply]
>  `path: custom.Foo`

If JsonSchema has a custom type, then that makes sense.
But, I'm afraid that the name `path` will be in conflict.
`customTypePath` may better...
And, when `customTypePath` is in this schema, format may be not needed.
```yaml
"$schema": http://json-schema.org/draft-07/schema#
type: object
properties:
  User:
    type: object
    properties:
      foo:
        customTypePath: custom.Foo
        type: string  
      bar:
        customTypePath: custom.bar
        type: number  
```
