### DISCUSSION TITLE
Support for const keyword in jsonshema

### DISCUSSION THREAD

**Discussion by gk12277** [koxudaxi/datamodel-code-generator#612] [General]
Jsonschema supports a keyword const 

```yaml
type: object
properties:
  foo:
    config:
      eid: 1
    type: object
    properties:
      bar:
        cont: "ABCD"
```
But when generating with this there is no change in the generated file.
