### ISSUE TITLE
Issue with enum default values and AllOf

### ISSUE THREAD

**Issue by fft001** [koxudaxi/datamodel-code-generator#1054]
**Describe the bug**

A default string literal does not seem to be populated when a AllOf reference is used in the same schema.

When generating with 0.16.x I get the following model: 

``` python
# generated by datamodel-codegen:
#   filename:  single_enum.yml
#   timestamp: 2023-01-26T13:03:37+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel
from typing_extensions import Literal


class Timestamp(BaseModel):
    timestamp: datetime


class Model(Timestamp):
    some_field: Literal['enum_value']
```

**To Reproduce**

Example schema:
single_enum.yml :
```yaml 
---
type: object
required: 
  - some_field
allOf:
  - $ref : timestamp.yml
properties:
  some_field:
    type: string
    enum: [enum_value]
    default: enum_value
```
and timestamp.yml :
``` yaml 
---
type: object
required: 
  - timestamp
properties:
  timestamp:
    type: string
    format: date-time
```

Used commandline:
```
$ datamodel-codegen --input single_enum.yml  --enum-field-as-literal one --set-default-enum-member --use-default
```

**Expected behavior**

I expect the output to be :
```
class Model(Timestamp):
    some_field: Literal['enum_value'] = 'enum_value'
```
This is the output from `0.14.0`
``` python
# generated by datamodel-codegen:
#   filename:  single_enum.yml
#   timestamp: 2023-01-26T12:59:44+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel
from typing_extensions import Literal


class Timestamp(BaseModel):
    timestamp: datetime


class Model(Timestamp):
    some_field: Optional[Literal['enum_value']] = 'enum_value'

```

expecting to see the 

**Version:**
 - OS: ubuntu 18.04
 - Python version: Python 3.11.1
 - datamodel-code-generator version: 0.16.0 and 0.16.1

**Additional context**

Without the allOf the output looks fine:

``` python
# generated by datamodel-codegen:
#   filename:  single_enum.yml
#   timestamp: 2023-01-26T13:09:03+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from typing_extensions import Literal


class Model(BaseModel):
    some_field: Optional[Literal['enum_value']] = 'enum_value'
```

Thanks!
