### ISSUE TITLE
Can't get Extra.forbid using the command line 

### ISSUE THREAD

**Issue by Roobxyz** [koxudaxi/datamodel-code-generator#1155]
Hello -- this forbid line (line 230) never gets hit and I think the default is `Extra.ignore` meaning there's no easy way to enforce strict type checking. The inline If statement just checks to see if `additionalProperties` or `allow_extra_fields` is set, but, if say addtionalProperties was set to `{'extra':'Extra.forbid'}` I think this line would set it back to `Extra.allow`.

https://github.com/koxudaxi/datamodel-code-generator/blob/97d4928782593efb1d439d91e7abbc70740b4ecd/datamodel_code_generator/model/pydantic/base_model.py#L224-L230

**Comment by koxudaxi** [comment]
@Roobxyz 
We can set `additionalProperties: false` to set `extra = Extra.forbid `
Input:
https://github.com/koxudaxi/datamodel-code-generator/blob/7947f4dbf3efd7cef9209fa72660fb0a036f21c1/tests/data/openapi/additional_properties.yaml#L139-L149

Output:
https://github.com/koxudaxi/datamodel-code-generator/blob/7947f4dbf3efd7cef9209fa72660fb0a036f21c1/tests/data/expected/parser/openapi/openapi_parser_parse_additional_properties/with_import_format.py#L39-L44

**Comment by git-malu** [comment]
```
components:
  schemas:
    AuthorizationSchema:
      $ref: "pap5.yaml#/components/schemas/AuthorizationSchema"
```


what if I'm referencing a schema, "AuthorizationSchema" for example, and I can't modify it directly since it's provided by others.

I have tried the method below, but it works for data model generator, but my editor complains "Schema validation: Property 'additionalProperties' is not allowed"
```
components:
  schemas:
    AuthorizationSchema:
      $ref: "pap5.yaml#/components/schemas/AuthorizationSchema"
      additionalProperties: false
```
Is this the right way to do it?
@koxudaxi
