### ISSUE TITLE
Wrong maximum value for integer in output model

### ISSUE THREAD

**Issue by pfaizian** [koxudaxi/datamodel-code-generator#1211]
I'm encountering a strange case when I try to generate python models for integers.

This is my input schema:
```
definitions:
  testInt64:
    type: integer
    minimum: 2097152
    maximum: 9223372036854775807
```
and this is the output model:
```
class TestInt64(BaseModel):
    __root__: conint(ge=2097152, le=9223372036854775808)
```

Please note that the maximum values are off by 1.

I'm using `datamodel-codegen` version `0.17.1` and `--target-python-version=3.8`
