### ISSUE TITLE
how to eliminate Optional when using default_factory? cant be None - confuses mypy.

### ISSUE THREAD

**Issue by tommyjcarpenter** [koxudaxi/datamodel-code-generator#1216]
this is the pydantic field output:

```
resource_type_allowlist_write: Optional[List[str]] = Field(
    default_factory=list,
    description="i"
)
```

generated from the following openapi field

```
resource_type_allowlist_write:
    description: i.
    type: array
        items:
        type: string
    default_factory: list
```

where this field is not `required`

But when there is a `default_factory`, there should be no `Optional`, because Optional means it can be `None`, but because there is a `default_factory` here, it cant be `None`, it is always at least `[]`

This is really the critical feature i was hoping for with default factory - to eliminate tons of problems with the generation saying things can be none when they have default factories
