### ISSUE TITLE
Incorrect filed order in dataclass

### ISSUE THREAD

**Issue by ostr00000** [koxudaxi/datamodel-code-generator#1283]
**Describe the bug**
Fields with default values are generated before fields without default - this is invalid python code.

**To Reproduce**

Example schema:
```yml
components:
  schemas:
    Note:
      type: object
      required:
        - text
      properties:
        author:
          type: string
        text:
          type: string
```

Used commandline:
```
$ datamodel-codegen --input api.yml --output api.py --target-python-version=3.6 --output-model-type=dataclasses.dataclass --input-file-type=openapi
```
**Generated code**
```python
from dataclasses import dataclass
from typing import Optional

@dataclass
class Note:
    author: Optional[str] = None
    text: str

```
**Expected behavior**
All fields without default should be before any field with default.

**Version:**
 - OS: Ubuntu 18.04
 - Python version: python3.7
 - datamodel-code-generator version: 0.18.1

**Additional context**
Similar problem reported in comment https://github.com/koxudaxi/datamodel-code-generator/issues/407#issuecomment-1437451354.

As a quick workaround, I changed this [line](https://github.com/koxudaxi/datamodel-code-generator/blob/3c6958275a7a2793b4f91b1709660fd86779b88c/datamodel_code_generator/model/dataclass.py#L49) to 
```python
self.fields.sort(key=lambda x: (-x.required, str(x)), reverse=False)
```
but I am not sure if this is a correct solution - there are a lot of fields like `has_default`, `default`, etc.
