### ISSUE TITLE
Discriminator propertyName for a union type array is not used when generating pydantic code

### ISSUE THREAD

**Issue by mesfahanisimscale** [koxudaxi/datamodel-code-generator#1472]
**Describe the bug**
When the schema includes an `array` type field, which is a union type with a discriminator, the discriminator `propertyName` doesn't make it to generated python code.

**To Reproduce**

Example schema:
```yaml
---
"$defs":
  FirstSchema:
    properties:
      type:
        const: FIRST_TYPE
        default: FIRST_TYPE
        title: Type
      other_prop:
        type: integer
    required:
      - other_prop
    title: FirstSchema
    type: object
  SecondSchema:
    properties:
      type:
        const: SECOND_TYPE
        default: SECOND_TYPE
        title: Type
      other_prop:
        type: boolean
    required:
      - other_prop
    title: SecondSchema
    type: object
  Force:
    properties:
      type:
        const: FORCE
        default: FORCE
        title: Type
    title: Force
    type: object
properties:
  my_array:
    items:
      discriminator:
        mapping:
          FIRST_TYPE: "#/$defs/FirstSchema"
          SECOND_TYPE: "#/$defs/SecondSchema"
        propertyName: type
      oneOf:
      - "$ref": "#/$defs/FirstSchema"
      - "$ref": "#/$defs/SecondSchema"
    type: array
required:
- my_array
title: MySchema
type: object

```

Used commandline:
```
$ datamodel-codegen --input ./schema.yaml --output ./output.py --output-model-type pydantic_v2.BaseModel  --input-file-type jsonschema
```

**Expected behavior**
The discriminator property name should end up in the generated python code. Similar to this:
```python
class MySchema(BaseModel):
    my_array: list[
       Annotated[
          Union[FirstSchema, SecondSchema],
          Field(discriminator="type")
        ]
      ]
```
As oppose to the current output:
```python
class MySchema(BaseModel):
    my_array: List[Union[FirstSchema, SecondSchema]]
```

**Version:**
 - OS: MacOS
 - Python version: 3.10.12
 - datamodel-code-generator version: 0.21.2

**Additional context**

the schema above is  what pydantic's `model_json_schema` method generates, when the `my_array: list[Annotated[Union[FirstSchema, SecondSchema], Field(discriminator="type")]]` is used.

You can find more information in this Github discussion on the pydantic repository.

https://github.com/pydantic/pydantic/discussions/3754
