### ISSUE TITLE
Missing constr import when --collapse-root-models and using directory input

### ISSUE THREAD

**Issue by indrat** [koxudaxi/datamodel-code-generator#1495]
**Describe the bug**
When using a directory input and multiple input files the resulting python module is missing a `from pydantic import constr`

Note that this occurs for both pydantic v1 and pydantic v2 output types.

**To Reproduce**

```
$ tree schemas
schemas
├── common.yml
└── test.yml

$ datamodel-codegen --input schemas --input-file-type jsonschema --output src --disable-timestamp --enable-version-header --collapse-root-models --output-model-type pydantic_v2.BaseModel

$ tree src
src
├── __init__.py
├── common.py
└── test.py

# Note the missing constr import in the `from pydantic ...` line
$ cat test.py
# generated by datamodel-codegen:
#   filename:  test.yml
#   version:   0.21.4

from __future__ import annotations

from pydantic import BaseModel, Field

from . import common


class Test(BaseModel):
    uid: constr(pattern=r'[0-9ABCDEFGHJKMNPQRSTVWXYZ]{26,26}') = Field(
        ..., description='ulid of this object'
    )
```

Example schema:
- schemas/common.yml
```yaml
---
$schema: https://json-schema.org/draft/2020-12/schema
$id: common.yml
definitions:
  ulid:
    type: string
    pattern: '[0-9ABCDEFGHJKMNPQRSTVWXYZ]{26,26}'
```
- schemas/test.yml
```yaml
---
$schema: https://json-schema.org/draft/2020-12/schema
$id: test.yml
title: test
required:
  - uid
properties:
  uid:
    description: ulid of this object
    $ref: ./common.yml#/definitions/ulid
```

Used commandline:
```
$ datamodel-codegen --input schemas --input-file-type jsonschema --output src --disable-timestamp --enable-version-header --collapse-root-models --output-model-type pydantic_v2.BaseModel
```

**Expected behavior**
The import in `test.py` should include `constr`

eg:
```python
from pydantic import BaseModel, Field, constr
```

Without the `constr` import a `pydantic.errors.PydanticUserError` is raised stating that the model '... is not fully defined, you should define `constr`, then call ...rebuild.

Separately, `common.py` is generated with the `constr` import despite not using it in that module or having any other schema models defined in it and ends up being:
```python
# generated by datamodel-codegen:
#   filename:  common.yml
#   version:   0.21.4

from __future__ import annotations

from typing import Any

from pydantic import RootModel, constr


class Model(RootModel):
    root: Any
```

**Version:**
 - OS: Linux, debian 12.
 - Python version: 3.11
 - datamodel-code-generator version: 0.21.4

**Comment by indrat** [comment]
Actually probably a dupe of https://github.com/koxudaxi/datamodel-code-generator/issues/1444 although possibly not limited to the string types or the OpenAPI input.

Appears to affect any additional types from the RootModels that are collapsed:
`common.yml`
```yaml
---
$schema: https://json-schema.org/draft/2020-12/schema
$id: common.yml
definitions:
  ulid:
    type: string
    pattern: '[0-9ABCDEFGHJKMNPQRSTVWXYZ]{26,26}'
  stringMap:
    type: object
    patternProperties:
      .{1,}:
        type: string
```

`test.yml`
```yaml
---
$schema: https://json-schema.org/draft/2020-12/schema
$id: test.yml
title: test
required:
  - uid
properties:
  uid:
    description: ulid of this object
    $ref: ./common.yml#/definitions/ulid
  attributes:
    description: key(string)-value attributes of this object
    $ref: ./common.yml#/definitions/stringMap
```

command:
```bash
datamodel-codegen --input schemas \
 --input-file-type jsonschema \
 --output src --disable-timestamp \
  --enable-version-header \
  --collapse-root-models \
  --output-model-type pydantic_v2.BaseModel
```

`test.py`, note the missing imports to `Dict` and `constr`
```python
# generated by datamodel-codegen:
#   filename:  test.yml
#   version:   0.21.4

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from . import common


class Test(BaseModel):
    uid: constr(pattern=r'[0-9ABCDEFGHJKMNPQRSTVWXYZ]{26,26}') = Field(
        ..., description='ulid of this object'
    )
    attributes: Optional[Dict[constr(pattern=r'.{1,}'), str]] = Field(
        None, description='key(string)-value attributes of this object'
    )
```

The `common.py` contains the imports for the collapsed RootModels but those imports are unused in that module.
```python
# generated by datamodel-codegen:
#   filename:  common.yml
#   version:   0.21.4

from __future__ import annotations

# Dict imported but unused
from typing import Any, Dict

# constr imported but unused
from pydantic import RootModel, constr


class Model(RootModel):
    root: Any
```
