### ISSUE TITLE
Optional not generated for nullable array items defined according to OpenAPI 3.0 spec, despite using --strict-nullable

### ISSUE THREAD

**Issue by tfausten** [koxudaxi/datamodel-code-generator#1496]
Items in an array are not generated as `Optional`, despite adding the `nullable: true` property.

**To Reproduce**

Example schema:
```yaml
# test.yml
properties:
  list1:
    type: array
    items:
      type: string
      nullable: true
required:
  - list1
```

Used commandline:
```
datamodel-codegen --input test.yml --output model.py --strict-nullable
```

This generates a datamodel in which the list items are not nullable:
```py
class Model(BaseModel):
    list1: List[str]
```

**Expected behavior**

The definition for a nullable string is correct according to the OpenAPI 3.0 spec.
```yaml
type: string
nullable: true
```

So I would expect Optional array items to be generated:
```py
class Model(BaseModel):
    list1: List[Optional[str]]
```

**Version:**
 - OS: macOS 13.4.1
 - Python version: 3.11
 - datamodel-code-generator version: 0.21.4
