### ISSUE TITLE
Generated Field Class Conflicts with Pydantic Field Class

### ISSUE THREAD

**Issue by gwukelic** [koxudaxi/datamodel-code-generator#1508]
**Describe the bug**

I have a schema that creates an invalid Python file. The issue seems to be that the `Field` class being generated conflicts with `Field` class from pydantic. How can I fix this?

```
error: Expression of type "Field" cannot be assigned to declared type "str"
    "Field" is incompatible with "str" (reportGeneralTypeIssues)
```

**To Reproduce**

Unacceptable schema ❌
```yaml
# input.yaml
components:
  schemas:
    BadSchema:
      type: object
      properties:
        fields:
          type: array
          items:
            oneOf:
            - type: object
              properties:
                a:
                  type: string
            - type: object
              properties:
                b:
                  type: string
                  pattern: "^[a-zA-Z_]+$"
```

What I run in the command line:
```sh
datamodel-codegen \
    --input input.yaml \
    --input-file-type "openapi" \
    --output output.py \
    --output-model-type pydantic.BaseModel \
    --field-constraints
```

Output

```python
# output.py using the unacceptable input.yaml file
from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class FieldModel(BaseModel):
    a: Optional[str] = None


class Field(BaseModel):
    b: Optional[str] = Field(None, regex='^[a-zA-Z_]+$')


class BadSchema(BaseModel):
    fields: Optional[List[Union[FieldModel, Field]]] = None
```

**Version:**
 - OS: macOS Ventura Version 13.3.1
 - datamodel-code-generator version: 0.21.4
