### ISSUE TITLE
Support for remote $refs

### ISSUE THREAD

**Issue by ioggstream** [koxudaxi/datamodel-code-generator#156]
**Is your feature request related to a problem? Please describe.**

Remote $ref are not resolved

**Describe the solution you'd like**

Remote $ref to be resolved

**Describe alternatives you've considered**

Remote $refs are downloaded and converted to local refs by an external component

**Additional context**

```
components:
  schemas:
    Problem:
      $ref: "https://opensource.zalando.com/problem/schema.yaml#/Problem"

```
