### ISSUE TITLE
'NO' (enum value) -> `False_` ?

### ISSUE THREAD

**Issue by tommyjcarpenter** [koxudaxi/datamodel-code-generator#1653]
I have a really bizarre issue where the string 'NO' (ISO country code for Norway), as part of an enum, is getting serlialized to `False`

we have an enum of ISO codes that includes the literal string `'NO'`

```
    FsymSpecific:
      type: object
      additionalProperties: false
      required:
      - country_code
      properties:
        country_code:
            type: string
            example: US
            enum:
              - 'AE'
              - 'AR'
             ...
              - 'NL'
              - 'NO'
              - 'NZ'
             ...
```

using the generation flags:

`datamodel-codegen --strict-types str bool --set-default-enum-member --enum-field-as-literal one --input-file-type openapi --input apis/openapi_resolved.yaml --output indexapi_types/pydantic_v2_types.py --use-default  --strict-nullable --collapse-root-models --output-model-type pydantic_v2.BaseModel
black indexapi_types/pydantic_v2_types.py`

we get the following output!

```
class CountryCode(Enum):
    AE = "AE"
    AR = "AR"
    ...
    NL = "NL"
    False_ = False
    NZ = "NZ"
    ...
```

`'NO'` becomes `False`! Can you please let me know how to not do that?

Thanks much
