### ISSUE TITLE
Enum default value type

### ISSUE THREAD

**Issue by aldoshkind** [koxudaxi/datamodel-code-generator#1742]
**Describe the bug**
Hello! I have schema like this:
```
    ReportState:
      type: string
      default: "Preparation"
      enum:
      - "Preparation"
      - "Processing"
      - "Ready"
```
And generated code is like this:
```
class ReportInfo(BaseModel):
    name: str
    uuid: UUID
    status: Optional[ReportState] = 'Preparation'
```
I think default value must be explicitly constructed to match enum type like this:
```
class ReportInfo(BaseModel):
    name: str
    uuid: UUID
    status: Optional[ReportState] = ReportState('Preparation')      # <-- here
```

 - datamodel-code-generator version: 0.25.0

**Additional context**
Thanks for great tool!
