### ISSUE TITLE
pydantic.errors.PydanticUserError: `unique_items` is removed, use `Set` instead

### ISSUE THREAD

**Issue by aldoshkind** [koxudaxi/datamodel-code-generator#1743]
**Describe the bug**
When trying to describe array with `uniqueItems: true` generated code is `sources: Optional[List[SourceDescription]] = Field([], unique_items=True)` and Pydantic says `'unique_items' is removed, use 'Set' instead`

**To Reproduce**

Example schema:
```
components:
  schemas:
...
        sources:
          type: array
          uniqueItems: true
          default: []
          items:
...
```

**Expected behavior**
`sources: Optional[List[SourceDescription]] = Field(Set[...])`

**Version:**
 - Python version: 3.10
 - datamodel-code-generator version: 0.25.0
