### ISSUE TITLE
Cannot override a $ref field to make it required

### ISSUE THREAD

**Issue by JeTondsLeGazon** [koxudaxi/datamodel-code-generator#1802]
**Describe the bug**
I would like to set a field passed from a $ref (let's say A) as `required`. If I simply put it in the `required` on my schema (let's say B), then I get some import errors.

If I follow another syntax, like [here](https://stackoverflow.com/questions/65080965/in-openapi-how-to-make-some-fields-of-a-referenced-schema-required), I get no import error but the field is simply not required 

**To Reproduce**
Create a simple folder `<my-folder>` and place these two files:
```yaml
---
type: object
title: A
properties:
  a_field: 
    type: string
    enum: [base_schema]
    default: base_schema
```

```yaml
---
type: object
title: B
allOf:
  - A
required:
  - a_field
```
Of course, here I could simply set `a_field` as required directly in `A` but this is just a basic example.

Or this one with the other syntax tried:
```yaml
---
type: object
title: B
allOf:
  - A
    required:
      - a_field
```
**Command to generate models**
Run:
`datamodel-codegen --input-file-type jsonschema --input <my-folder> --output <output-folder>`

For some reason, I cannot make it work with `yaml` as input-file-type ...

**Expected behavior**
I expect the `B` model to be generated like this (or something alike):
```python
from __future__ import annotations

from enum import Enum

class AField(Enum):
    base_schema = 'base_schema'

class B():
    a_field: AField = 'base_schema'
```
We could also imagine importing `AField` from file `A`

Instead I either get this (with the import errors):
```python
from __future__ import annotations

from .a import A


class B(A):
    a_field: AField

```
Or this one with the field not required:
```python
from __future__ import annotations

from .a import A


class B(A):
    pass

```
**Version:**
 - OS: Windows + Linux
 - Python version: 3.11
 - datamodel-code-generator version: 0.25.1
