### ISSUE TITLE
yaml support is not complete

### ISSUE THREAD

**Issue by ioggstream** [koxudaxi/datamodel-code-generator#182]
**Describe the bug**
Parsing yaml OAS3 files does not work

**To Reproduce**
See #183 .

Example schema:
```yaml
components:
  schemas:
    Problem:
      $ref: https://teamdigitale.github.io/openapi/0.0.6/definitions.yaml#/schemas/Problem

```

Used commandline:
```
$ datamodel-codegen test.yaml
``

**Expected behavior**
A generated Problem class

**Version:**
 - OS: linux
 - Python Verison: 3.7
 - datamodel-code-generator Version latest
