### ISSUE TITLE
Support for pyproject.toml

### ISSUE THREAD

**Issue by joshbode** [koxudaxi/datamodel-code-generator#188]
`datamodel-codegen` is gaining a lot of command-line options which is great, but it can make the invocation quite lengthy.

How about adding support for a `pyproject.toml` section, e.g.
```toml
[tool.datamodel-codegen]
field-constraints = true
snake-case-field = true
strip-default-none = false
target-python-version = "3.7"
```

I'm happy to add this if there is desire for this feature :)
