### ISSUE TITLE
Use schema description to populate class docstring

### ISSUE THREAD

**Issue by Liam-Deacon** [koxudaxi/datamodel-code-generator#274]
I'd like to be able to retain my openapi schema descriptions in the generated python code, e.g.

```yaml
components:
  schemas:
    MyClass:
      description: >-
        My classes description goes here...
      type: object
      properties: {}
```

Which I would like to be preserved in the conversion process to python, e.g.

```python
class MyClass(BaseModel):
    """
    My class description goes here...
    """
    ...
```

Is this easy to implement? I'd be happy to raise a PR, I'm not sure where to start looking in the codebase though!
