### ISSUE TITLE
Generated intermediate models may shadow imports

### ISSUE THREAD

**Issue by ofek** [koxudaxi/datamodel-code-generator#332]
Hey, great library, thank you!

**Describe the bug**

See `Optional`

**To Reproduce**

Example schema:

```yaml
components:
  schemas:
    Config:
      properties:
        optional:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
```

Used commandline:
```
$ datamodel-codegen --input-file-type openapi --strip-default-none --input test.yaml --output model.py
```

Produced:

```python
from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel


class Optional(BaseModel):
    __root__: List[str]


class Config(BaseModel):
    optional: Optional[Dict[str, Optional]]
```

**Version:**
 - OS: Windows 10
 - Python version: 3.8
 - datamodel-code-generator version: 0.7.2
