### ISSUE TITLE
oneOf is not treated the same as anyOf

### ISSUE THREAD

**Issue by ofek** [koxudaxi/datamodel-code-generator#333]
**Describe the bug**

The docs indicate that they are both treated as `typing.Union`

**To Reproduce**

Example schema:

```yaml
components:
  schemas:
    Config:
      properties:
        setting:
          type: object
          additionalProperties:
            oneOf:  # anyOf
            - type: string
            - type: array
              items:
                type: string
```

Used commandline:

```
$ datamodel-codegen --input-file-type openapi --strip-default-none --input test.yaml --output model.py
```

`oneOf`:

```python
from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Extra


class Setting(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: Any


class Config(BaseModel):
    setting: Optional[Dict[str, Setting]]
```

`anyOf`:

```python
from __future__ import annotations

from typing import Dict, List, Optional, Union

from pydantic import BaseModel, Extra


class Setting(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: Union[str, List[str]]


class Config(BaseModel):
    setting: Optional[Dict[str, Setting]]
```

**Version:**
 - OS: Windows 10
 - Python version: 3.8
 - datamodel-code-generator version: 0.7.2
