### ISSUE TITLE
Support for adding validator decorator

### ISSUE THREAD

**Issue by sarangsbabu367** [koxudaxi/datamodel-code-generator#464]
**Is your feature request related to a problem? Please describe.**
`pydantic` supports the provision to add a validator decorator for fields. Is there anyway to represent this in `jsonschema` and data-model-generator will generate this. This can be treated as a `custom-path` where decorator code will be present in the given path and during the model generation this method needs to be attached to the model(Not sure about this).

**Describe the solution you'd like**
* Support for specifying [validator](https://pydantic-docs.helpmanual.io/usage/validators/) in `jsonschema`.
* Need a provision to specify validators in the jsonschema and data-model generator should recognize this.
```python
from pydantic import BaseModel, ValidationError, validator

class UserModel(BaseModel):
    name: str

    @validator('name', pre=True)
    def name_must_contain_space(cls, v):
        if ' ' not in v:
            raise ValueError('must contain a space')
        return v.title()
```
* `validator` name and args can be described in `jsonschema` and `path` to the code can be made custom, since it will contain other logic.
```yaml
type: object
properties:
  name:
    type: string
    x-validator:
      type: object
      properties:
        name:
          const: name_must_contain_space
        args:
          pre:
          const: True
```

**Describe alternatives you've considered**
* For implementing this behaviour, generated models needs to be extended and need to add this validator method in the extended model.

**Comment by koxudaxi** [comment]
@sarangsbabu367 
Thank you for your suggestion.
I feel it's a good idea.
I will implement it when I finish other issues.

**Comment by sarangsbabu367** [comment]
@koxudaxi  May i open a pr for this ?

1. Can you suggest some points to improve the validator representation in `yaml`, like currently there is an option for `customTypePath` can we use a similar name like `customValidator` ?
2. Can we reduce the `yaml` format(minimalize) ?

```yaml
Person:
  type: object
  customValidator:
    type: object
    properties:
      path: a.b.c.person_root_validator
      args:
        pre: True
  properties:
    name:
      type: string
      customValidator:
        type: object
        properties:
          path: a.b.c.name_must_contain_space
          args:
            pre: True
            always: True
```
In the above example, we can support an option for `root-level` validator. And option to give a validator name can be removed since there wont be much usecase(validator method name will be same as given by client)
