### ISSUE TITLE
Generate enum class as an inner class when defined in a model

### ISSUE THREAD

**Issue by cansukaynak** [koxudaxi/datamodel-code-generator#513]
When an enum is defined as part of a model, the enum class generated is a standalone class.

For example, for

```
Model:
   ...
   properties:
      enumDefinition:
         type: ...
         enum:
            - x
            - y
```

an enum class named `EnumDefinition` would be generated.

This would result in generation of enum classes like `EnumDefinition`, `EnumDefinition1`, `EnumDefinition2` etc. when the same enum property name is defined across different models.

Instead of this, would it be possible to generate an enum class as an inner class of the model class, in which they are defined as a property?
For the example above, each model with `enumDefinition` property would have its own inner class `EnumDefinition`.
