### ISSUE TITLE
__root__ field in the list item class

### ISSUE THREAD

**Issue by cansukaynak** [koxudaxi/datamodel-code-generator#531]
When I define a property like 
```
Model:
        someList:
            type: array
            items:
                type: string
```

The generated pydantic model looks like:

```
class SomeListItem(BaseModel):
    __root__: str = Field(..., max_length=18, min_length=9)

...

class Model:
    ...
    (
        someList: Sequence[someListItem] = Field(
        ...,
        description="some description",
    )
```

To access the value in a SomeListItem instance, one would need to access the `__root__` field, which is a private field. Would it be possible to also generate an accessor function, something like

```
def get_value():
   return  __root__
```
inside the `SomeListItem` class to avoid access to this private field?

If not, is there any other recommended way of accessing the `__root__` field? Or maybe generating a public field, instead of a private field?
