### ISSUE TITLE
Option to add Config details to specific classes

### ISSUE THREAD

**Issue by gk12277** [koxudaxi/datamodel-code-generator#553]
**Is your feature request related to a problem? Please describe.**
There are a number of options which can be given for Config class. Need a option to define config and its attributes for a particular class which will be generated.

**Describe the solution you'd like**
Need a way to specify that a specific class should have a config class with some options
```yaml
type: object
properties:
    Foo:
       type: object
       properties:
         name:
            type: string
```
Need some way to specify that generated class Foo should have a config class with `arbitrary_types_allowed = True.`

```python
class Foo:
  
  Class Config:
        arbitrary_types_allowed = True
``` 

Here class Foo has Config with `arbitrary_types_allowed`
