### ISSUE TITLE
BaseClass for enums by enum type

### ISSUE THREAD

**Issue by adaamz** [koxudaxi/datamodel-code-generator#617]
**Is your feature request related to a problem? Please describe.**
The problem is that when I want to serialize int/str enum that is child of enum.Enum i got this error
```
value is not a valid enumeration member; permitted: 1, 2, 3
```
for code
```python
Asdf(enum_abc=EnumAbc.A)
```
because the EnumAbc is child of enum.Enum and not enum.IntEnum (i have no more detailed description for this problem, but it just works)
```python
class EnumAbc(Enum):
  A = 1
  B = 2
  C = 3
```

**Describe the solution you'd like**
I would like to specify (implicitely deducted by type or somehow explicitely) the parent of each enum.
```yaml
components:
  schemas:
    EnumAbc:
      type: integer
      enum: [1, 2, 3]
      x-enum-varnames: [A, B, C]
```
should generate this python code:
```python
from enum import IntEnum

class EnumAbc(IntEnum):
    A = 1
    B = 2
    C = 3
```

or for string enums:
```yaml
components:
  schemas:
    StringEnumAbc:
      type: string
      enum: ["a", "b", "c"]
```
should generate this python code:
```python
from enum import Enum

class StringEnumAbc(str, Enum):
    A = "a"
    B = "b"
    C = "c"
```
(or lowercased names, i already changed this in my template 😁)

**Describe alternatives you've considered**
implicitely or explicitely as stated before :)
by explicitely i mean sth like this
```yaml
components:
  schemas:
    EnumAbc:
      type: integer
      x-base-class: enum.IntEnum
      enum: [1, 2, 3]
      x-enum-varnames: [A, B, C]
```
respectively
```yaml
components:
  schemas:
    StringEnumAbc:
      type: string
      x-base-class: str
      enum: ["a", "b", "c"]
```

**Comment by ghandic** [comment]
Any progress on this?

**Comment by koxudaxi** [comment]
I'm sorry for my too-late reply.
Have you tried the  `--use-subclass-enum ` option?
```bash
  --use-subclass-enum   Define Enum class as subclass with field type when
                        enum has type (int, float, bytes, str)
```

```python
# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-12-28T16:38:03+00:00

from __future__ import annotations

from enum import Enum


class EnumAbc(int, Enum):
    A = 1
    B = 2
    C = 3


class StringEnumAbc(str, Enum):
    a = 'a'
    b = 'b'
    c = 'c'
```

oepnapi.yaml
```yaml
components:
  schemas:
    EnumAbc:
      type: integer
      enum: [1, 2, 3]
      x-enum-varnames: [A, B, C]
    StringEnumAbc:
      type: string
      enum: [ "a", "b", "c" ]

```
