### ISSUE TITLE
Timestamp with timezone format string type is generated as a string property of the pydantic model

### ISSUE THREAD

**Issue by dreinon** [koxudaxi/datamodel-code-generator#642]
Fields with schema
```yaml
schema:
        type: string
        format: timestamp with time zone
```
are generated as string properties of the pydantic models instead of being generated as a datetime property, whereas
```yaml
schema:
        type: string
        format: date
```
is correctly generated as date.
