### ISSUE TITLE
Use schema description to populate field docstring

### ISSUE THREAD

**Issue by ClausHolbechArista** [koxudaxi/datamodel-code-generator#857]
Similar to #274 I would like to add docstrings for each _field_ based on the jsonschema description. Purpose is for my IDE (VSCode) to pick up the description and show in mouse-over

```yaml
{
  "type": "object",
  "properties": {
    "mykey": {
      "type": "string",
      "description": "Field description"
    }
  }
}
```

Would lead to:

```python
class Model(BaseModel):
    mykey: Optional[str] = Field(None, description='Field description')
    """
    Field description
    """
```

Maybe I am missing something else that could solve this, so I welcome alternative solutions.

I can try to submit a PR for this, if you agree that it would be useful.
